### ISSUE TITLE
Where are the definitions of Selection and Attention Losses?

### ISSUE THREAD

**Issue by JunMa11** [zmbhou/SALTMM#1]
Dear @zmbhou ,

Thanks for sharing the code.

Could you give me some guidances about the definitions of Selection and Attention Losses?

Best regards,
Jun

**Comment by zmbhou** [comment]
Hi, I have not release the code for mask scoring base selection which works on the selected annotations. Hence the selection loss depends on the results of mask scoring. The details of classification networks for attention loss is displayed in modelVGGASSPattention.py

**Comment by zmbhou** [comment]
Hi, I have not released the code for mask scoring base selection loss yet. The selection loss works on the selected proxy annotations and it depends on the results of mask scoring. The details of classification networks for attention loss is displayed in modelVGGASSPattention.py

**Comment by JunMa11** [comment]
Thanks for your kindly reply very much.
